/**
 * System Enums and Constants Definition
 * OmniCommerce Enterprise
 */

const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
  DELIVERY_PERSON: 'DELIVERY_PERSON',
  SELLER: 'SELLER',
  SUPPORT: 'SUPPORT',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAID: 'PAID',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  PACKED: 'PACKED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  ASSIGNED_TO_DELIVERY: 'ASSIGNED_TO_DELIVERY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURNED: 'RETURNED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  CAPTURED: 'CAPTURED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

const PAYMENT_METHODS = {
  STRIPE_CREDIT_CARD: 'STRIPE_CREDIT_CARD',
  PAYPAL: 'PAYPAL',
  RAZORPAY: 'RAZORPAY',
  CASH_ON_DELIVERY: 'CASH_ON_DELIVERY'
};

const SHIPPING_CARRIERS = {
  FEDEX: 'FedEx Express',
  UPS: 'UPS Ground',
  USPS: 'USPS Priority',
  DHL: 'DHL Express'
};

const INVENTORY_ALERT_LEVELS = {
  IN_STOCK: 'IN_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK'
};

const NOTIFICATION_TYPES = {
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_PACKED: 'ORDER_PACKED',
  ORDER_DISPATCHED: 'ORDER_DISPATCHED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  LOW_STOCK: 'LOW_STOCK',
  SYSTEM: 'SYSTEM'
};

const AUDIT_EVENT_TYPES = {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_PACKED: 'ORDER_PACKED',
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  DELIVERY_OUT: 'DELIVERY_OUT',
  DELIVERY_CONFIRMED: 'DELIVERY_CONFIRMED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  PAYMENT_PROCESSED: 'PAYMENT_PROCESSED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
  COUPON_CREATED: 'COUPON_CREATED'
};

module.exports = {
  USER_ROLES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  SHIPPING_CARRIERS,
  INVENTORY_ALERT_LEVELS,
  NOTIFICATION_TYPES,
  AUDIT_EVENT_TYPES
};
