/**
 * System Enums and Constants Definition
 * OmniCommerce Enterprise
 */

const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  SELLER: 'SELLER',
  ADMIN: 'ADMIN',
  SUPPORT: 'SUPPORT'
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  CAPTURED: 'CAPTURED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

const PAYMENT_METHODS = {
  STRIPE_CREDIT_CARD: 'STRIPE_CREDIT_CARD',
  PAYPAL: 'PAYPAL',
  RAZORPAY: 'RAZORPAY',
  CASH_ON_DELIVERY: 'CASH_ON_DELIVERY'
};

const SHIPPING_CARRIERS = {
  FEDEX: 'FedEx Express',
  UPS: 'UPS Ground',
  USPS: 'USPS Priority',
  DHL: 'DHL Express'
};

const INVENTORY_ALERT_LEVELS = {
  IN_STOCK: 'IN_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK'
};

const AUDIT_EVENT_TYPES = {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  PAYMENT_PROCESSED: 'PAYMENT_PROCESSED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED'
};

module.exports = {
  USER_ROLES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  SHIPPING_CARRIERS,
  INVENTORY_ALERT_LEVELS,
  AUDIT_EVENT_TYPES
};
